include "application"

database {
  url = "jdbc:mysql://localhost:3306/danddKot"
  url = ${?DATABASE_URL}
  user = "root"
  user = ${?DATABASE_USER}
  password = "my-secret-pw"
  password = ${?DATABASE_PASSWORD}
}
